//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ictshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int ID { get; set; }
        public string HoTen { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string DonGia { get; set; }
        public string SoLuong { get; set; }
        public string Tien { get; set; }
    }
}
